name: build

on:
  push:
    branches: [$default-branch, shain/*]
  pull_request:
    branches: [$default-branch]

jobs:
  gather_requirements:
    runs-on: ubuntu-latest
    container: almalinux:latest
    steps:
      - uses: actions/checkout@v3
      - run: ls -la
      - run: scripts/docker_xfce.sh
